// samples/angular2/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

import { TodoWithID, Todo, TodosService } from './todos.service';

@Component({
  selector: 'app-root',
  template: `<div>
    <h1>Angular 2 + Dexie Todo Example</h1>
    <app-add-todo (addTodo)="onAddTodo($event)"></app-add-todo>
    <app-todo-list
      [todos]="todosList"
      (toggleTodo)="onToggleTodo($event)"
      (deleteTodo)="onDeleteTodo($event)"
    ></app-todo-list>
  </div>`,
})
export class AppComponent implements OnInit {
  todosList: Array<TodoWithID> = [];
  constructor(private todosService: TodosService) {}

  ngOnInit() {
    this.todosService.getAll().then((todos: Array<TodoWithID>) => {
      this.todosList = todos;
    });
  }

  onAddTodo(title: string) {
    const todo: Todo = {
      title,
      done: false,
    };
    this.todosService
      .add(todo)
      .then((id) => {
        this.todosList = [...this.todosList, Object.assign({}, todo, { id })];
      });
  }

  onToggleTodo({ id, done }: { id: number, done: boolean }) {
    this.todosService
      .update(id, { done })
      .then(() => {
        const todoToUpdate = this.todosList.find((todo) => todo.id === id);
        this.todosList = [...this.todosList.filter((todo) => todo.id !== id), Object.assign({}, todoToUpdate, { done })];
      });
  }

  onDeleteTodo(id: number) {
    this.todosService
      .remove(id)
      .then(() => {
        this.todosList = this.todosList.filter((todo) => todo.id !== id);
      });
  }
}

// samples/react/src/App.js
import React, { Component } from 'react';
import './App.css';

import db from './db';
import AddTodo from './AddTodo';
import TodoList from './TodoList';

class App extends Component {
  constructor() {
    super();
    this.state = { todos: [] };
    this.handleAddTodo = this.handleAddTodo.bind(this);
    this.handleDeleteTodo = this.handleDeleteTodo.bind(this);
    this.handleToggleTodo = this.handleToggleTodo.bind(this);
  }

  componentDidMount() {
    db.table('todos')
      .toArray()
      .then((todos) => {
        this.setState({ todos });
      });
  }

  handleAddTodo(title) {
    const todo = {
      title,
      done: false,
    };
    db.table('todos')
      .add(todo)
      .then((id) => {
        const newList = [...this.state.todos, Object.assign({}, todo, { id })];
        this.setState({ todos: newList });
      });
  }

  handleToggleTodo(id, done) {
    db.table('todos')
      .update(id, { done })
      .then(() => {
        const todoToUpdate = this.state.todos.find((todo) => todo.id === id);
        const newList = [
          ...this.state.todos.filter((todo) => todo.id !== id),
          Object.assign({}, todoToUpdate, { done })
        ];
        this.setState({ todos: newList });
      });
  }

  handleDeleteTodo(id) {
    db.table('todos')
      .delete(id)
      .then(() => {
        const newList = this.state.todos.filter((todo) => todo.id !== id);
        this.setState({ todos: newList });
      });
  }

  render() {
    return (
      <div className="App">
        <div className="App-header">
          <h2>React + Dexie Todo Example</h2>
        </div>
        <AddTodo handleAddTodo={this.handleAddTodo} />
        <TodoList
          todos={this.state.todos}
          handleToggleTodo={this.handleToggleTodo}
          handleDeleteTodo={this.handleDeleteTodo}
        />
      </div>
    );
  }
}

export default App;
