// samples/react-suspense/src/AddTodo.js
import React, { useState } from 'react';

export function AddTodo ({handleAddTodo}) {
  const [value, setValue] = useState();
  return <div>
    <input type="text" value={value} onChange={ev => setValue(ev.target.value)} />
    <button type="button" onClick={() => handleAddTodo(value)}>Add Todo</button>
  </div>;
}

// samples/vue/src/components/AddTodo.vue
<template>
  <div role="group" aria-label="Add todo">
    <input type="text" v-model="value" />
    <button type="button" @click="addTodo">Add Todo</button>
  </div>
</template>

<script>
export default {
  name: 'AddTodo',
  components: {},
  data() {
    return {
      value: '',
    }
  },
  methods: {
    // addTodo emits an event to add a todo to the todo list.
    addTodo() {
      this.$emit('add-todo', { text: this.value });
      this.value = '';
    }
  }
}
</script>
